import slider1 from "../../Assets/Rectangle 95@3x.png";
import user from "../../Assets/user.png";
import location from "../../Assets/location.png";
import timer from "../../Assets/timer.png";
import users from "../../Assets/Group 3626.png";
import gift from "../../Assets/Icon awesome-gift.png";

export const SurveyCard = {
  current_user: [
    {
      img: slider1,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      date: "May, 1, 2021",
      id: "011",
    },
    {
      img: slider1,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      date: "May, 1, 2021",
      id: "012",
    },
    {
      img: slider1,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      date: "May, 1, 2021",
      id: "013",
    },
  ],
  all_user: [
    {
      img: slider1,
      proImg: user,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      name: "username",
      date: "May, 1, 2021",
      id: "014",
    },
    {
      img: slider1,
      proImg: user,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      name: "username",
      date: "May, 1, 2021",
      id: "015",
    },
    {
      img: slider1,
      proImg: user,
      locImg: location,
      cardNum: user,
      gift: gift,
      users: users,
      timer: timer,
      time: "2 Minutes",
      numUser: "1500+",
      numGift: "50",
      title: "Rising cataract issues in",
      body:
        "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonum eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
      location: "Lorem ipsum dolor sit",
      name: "username",
      date: "May, 1, 2021",
      id: "016",
    },
  ],
};
